Repository DependencyTrack/helm-charts, pull requests merged in 2024-06, with the labels that each got.

#73 Bump `appVersion` to `4.11.2`
  charts/dependency-track/Chart.yaml
Labels: enhancement

#75 Bump `appVersion` to `4.11.3`
  charts/dependency-track/Chart.yaml
Labels: enhancement

#84 List breaking changes separately in release notes
  .github/release.yml
Labels: documentation

#83 Specify `envFrom` as `array` instead of `object` to support `valueFrom`
  charts/dependency-track/Chart.yaml
  charts/dependency-track/README.md
  charts/dependency-track/ci/additional-pvc.yaml
  charts/dependency-track/ci/init-values.yaml
  charts/dependency-track/ci/pvc-values.yaml
  charts/dependency-track/ci/test-values.yaml
  charts/dependency-track/templates/api-server/statefulset.yaml
  charts/dependency-track/templates/frontend/deployment.yaml
  charts/dependency-track/values-minikube.yaml
  charts/dependency-track/values.yaml
Labels: enhancement, breaking change

#86 Add JSON schema for `values.yaml`
  charts/dependency-track/values.schema.json
Labels: enhancement

#77 Migrate `hyades` chart from `DependencyTrack/hyades`
  charts/hyades/Chart.yaml
  charts/hyades/README.md
  charts/hyades/ci/test-values.yaml
  charts/hyades/templates/_helpers.tpl
  charts/hyades/templates/api-server/deployment.yaml
  charts/hyades/templates/api-server/ingress.yaml
  charts/hyades/templates/api-server/service.yaml
  charts/hyades/templates/api-server/servicemonitor.yaml
  charts/hyades/templates/extra-manifests.yaml
  charts/hyades/templates/frontend/deployment.yaml
  charts/hyades/templates/frontend/ingress.yaml
  charts/hyades/templates/frontend/service.yaml
  charts/hyades/templates/mirror-service/deployment.yaml
  charts/hyades/templates/notification-publisher/deployment.yaml
  charts/hyades/templates/repo-meta-analyzer/deployment.yaml
  charts/hyades/templates/secret.yaml
  charts/hyades/templates/vuln-analyzer/service.yaml
  charts/hyades/templates/vuln-analyzer/statefulset.yaml
  charts/hyades/values-minikube.yaml
  charts/hyades/values.yaml
  ct.yaml
Labels: enhancement

#91 Port enhancement from `dependency-track` chart to `hyades`
  charts/hyades/templates/_helpers.tpl
  charts/hyades/templates/api-server/deployment.yaml
  charts/hyades/templates/api-server/ingress.yaml
  charts/hyades/templates/api-server/service.yaml
  charts/hyades/templates/frontend/deployment.yaml
  charts/hyades/templates/frontend/ingress.yaml
  charts/hyades/templates/frontend/service.yaml
  charts/hyades/templates/ingress.yaml
  charts/hyades/templates/mirror-service/deployment.yaml
  charts/hyades/templates/notification-publisher/deployment.yaml
  charts/hyades/templates/repo-meta-analyzer/deployment.yaml
  charts/hyades/templates/serviceaccount.yml
  charts/hyades/templates/vuln-analyzer/service-headless.yaml
  charts/hyades/templates/vuln-analyzer/service.yaml
  charts/hyades/templates/vuln-analyzer/statefulset.yaml
  charts/hyades/values-minikube.yaml
  charts/hyades/values.yaml
Labels: enhancement

#93 Use `create-topics.sh` script from `hyades` repository
  charts/hyades/ci/test-values.yaml
Labels: enhancement

#94 Add PostgreSQL and Redpanda to `values-minikube.yaml`
  charts/hyades/ci/test-values.yaml
  charts/hyades/values-minikube.yaml
Labels: enhancement

#97 Add values schema for `hyades` chart
  charts/hyades/Chart.yaml
  charts/hyades/templates/mirror-service/deployment.yaml
  charts/hyades/values.schema.json
  charts/hyades/values.yaml
Labels: enhancement

#107 Bump Dependency-Track version to 4.11.4
  charts/dependency-track/Chart.yaml
Labels: enhancement
