Repository DependencyTrack/helm-charts, pull requests merged in 2024-07, with the labels that each got.

#109 Bump Dependency-Track version to 4.11.5
  charts/dependency-track/Chart.yaml
  charts/dependency-track/README.md
Labels: enhancement

#110 Add registry override to apiServer and frontend
  charts/dependency-track/README.md
  charts/dependency-track/templates/_helpers.tpl
  charts/dependency-track/values.yaml
Labels: enhancement

#117 Add image registry override to `values.schema.json`
  charts/dependency-track/Chart.yaml
  charts/dependency-track/values.schema.json
  charts/dependency-track/values.yaml
Labels: enhancement

#122 Fix invalid JSON in `values.schema.json`
  charts/dependency-track/values.schema.json
Labels: defect

#125 Add registry overrides for hyades services
  charts/hyades/Chart.yaml
  charts/hyades/templates/_helpers.tpl
  charts/hyades/values.schema.json
  charts/hyades/values.yaml
Labels: enhancement

#120 Rename kafka topic prefix config for apache kafka compatibility
  charts/hyades/templates/api-server/deployment.yaml
  charts/hyades/templates/mirror-service/deployment.yaml
  charts/hyades/templates/notification-publisher/deployment.yaml
  charts/hyades/templates/repo-meta-analyzer/deployment.yaml
  charts/hyades/templates/vuln-analyzer/statefulset.yaml
Labels: enhancement

#123 Add default `podSecurityContext` to fix `/data` volume permissions
  charts/dependency-track/templates/api-server/deployment.yaml
  charts/dependency-track/templates/api-server/statefulset.yaml
  charts/dependency-track/values.schema.json
  charts/dependency-track/values.yaml
Labels: enhancement, breaking change
