Repository DependencyTrack/helm-charts, pull requests merged in 2024-05, with the labels that each got.

#42 add node-selector to helm chart
  charts/dependency-track/Chart.yaml
  charts/dependency-track/templates/api-server/statefulset.yaml
  charts/dependency-track/templates/frontend/deployment.yaml
  charts/dependency-track/values.yaml
Labels: enhancement

#45 Bump `appVersion` to `4.11.0`
  charts/dependency-track/Chart.yaml
  charts/dependency-track/values.yaml
Labels: enhancement

#47 Remove unstable warning from `README.md`
  README.md
Labels: documentation

#52 feat: Allow to override ServiceAccount
  charts/dependency-track/Chart.yaml
  charts/dependency-track/README.md
  charts/dependency-track/templates/_helpers.tpl
  charts/dependency-track/templates/api-server/statefulset.yaml
  charts/dependency-track/templates/frontend/deployment.yaml
  charts/dependency-track/templates/serviceaccount.yaml
  charts/dependency-track/values.yaml
Labels: enhancement

#58 Bump `appVersion` to `4.11.1`
  charts/dependency-track/Chart.yaml
Labels: enhancement

#57 Fix multi line annotations at services
  charts/dependency-track/Chart.yaml
  charts/dependency-track/ci/multi-line-annotations.yaml
  charts/dependency-track/templates/api-server/service.yaml
  charts/dependency-track/templates/frontend/service.yaml
Labels: defect

#68 Disable version increment check
  ct.yaml
Labels: enhancement
