Repository DependencyTrack/helm-charts, pull requests merged in 2024-04, with the labels that each got.

#9 Add basic usage instructions
  README.md
Labels: documentation

#10 Disable readOnlyRootFilesystem for config.json ENV vars
  charts/dependency-track/Chart.yaml
  charts/dependency-track/templates/frontend/deployment.yaml
Labels: bug

#13 Deployment Flexibility and Simplify Ingress Management - GKE deployment
  charts/dependency-track/Chart.yaml
  charts/dependency-track/README.md
  charts/dependency-track/ci/init-values.yaml
  charts/dependency-track/templates/api-server/ingress.yaml
  charts/dependency-track/templates/api-server/service.yaml
  charts/dependency-track/templates/api-server/statefulset.yaml
  charts/dependency-track/templates/frontend/deployment.yaml
  charts/dependency-track/templates/frontend/service.yaml
  charts/dependency-track/templates/ingress.yaml
  charts/dependency-track/values.yaml
Labels: enhancement

#21 Generate release notes
  .github/release.yml
  .github/workflows/helm-release.yml
  cr.yaml
Labels: documentation, enhancement

#22 Do not use `ingress.hostname` for `frontend.apiBaseUrl`
  charts/dependency-track/Chart.yaml
  charts/dependency-track/README.md
  charts/dependency-track/templates/frontend/deployment.yaml
Labels: defect

#25 Create `artifacthub-repo.yml` for Artifact Hub
  artifacthub-repo.yml
Labels: documentation

#24 Add Artifact Hub badge
  README.md
Labels: documentation

#23 Support `ingressClassName`, ingress `tls`, and `extraObjects`
  charts/dependency-track/Chart.yaml
  charts/dependency-track/templates/extra-manifests.yaml
  charts/dependency-track/templates/ingress.yaml
  charts/dependency-track/values.yaml
Labels: enhancement

#34 Fix API `apiServer.tolerations` being referenced in frontend deployment
  charts/dependency-track/Chart.yaml
  charts/dependency-track/templates/frontend/deployment.yaml
Labels: defect

#33 Add support for `additionalVolumes`
  charts/dependency-track/Chart.yaml
  charts/dependency-track/ci/additional-pvc.yaml
  charts/dependency-track/templates/api-server/statefulset.yaml
  charts/dependency-track/templates/frontend/deployment.yaml
  charts/dependency-track/values.yaml
Labels: enhancement
