Repository DependencyTrack/helm-charts, pull requests merged in 2024-08, with the labels that each got.

#128 Ensure `podSecurityContext` comments shows up in docs
  charts/dependency-track/values.yaml
Labels: documentation

#131 Fix persistent volume in deployment manifest
  charts/dependency-track/templates/api-server/deployment.yaml
Labels: defect

#133 Lower default hyades API server memory request and limit to 2Gi
  charts/hyades/values.yaml
Labels: enhancement

#138 Bump Dependency-Track version to 4.11.6
  charts/dependency-track/Chart.yaml
Labels: enhancement

#141 Bump Dependency-Track version to 4.11.7
  charts/dependency-track/Chart.yaml
Labels: enhancement

#144 Allow image tags to be specified as `sha256` digest
  charts/dependency-track/Chart.yaml
  charts/dependency-track/templates/_helpers.tpl
  charts/dependency-track/values.yaml
  charts/hyades/Chart.yaml
  charts/hyades/templates/_helpers.tpl
  charts/hyades/values.yaml
Labels: enhancement

#147 Make container `securityContext` configurable
  charts/dependency-track/templates/api-server/deployment.yaml
  charts/dependency-track/templates/api-server/statefulset.yaml
  charts/dependency-track/templates/frontend/deployment.yaml
  charts/dependency-track/values.yaml
  charts/hyades/templates/api-server/deployment.yaml
  charts/hyades/templates/frontend/deployment.yaml
  charts/hyades/templates/mirror-service/deployment.yaml
  charts/hyades/templates/notification-publisher/deployment.yaml
  charts/hyades/templates/repo-meta-analyzer/deployment.yaml
  charts/hyades/templates/vuln-analyzer/deployment.yaml
  charts/hyades/templates/vuln-analyzer/statefulset.yaml
  charts/hyades/values.yaml
  ct.yaml
Labels: enhancement

#146 Template `initContainers` and `extraContainers` values
  charts/dependency-track/Chart.yaml
  charts/dependency-track/templates/api-server/deployment.yaml
  charts/dependency-track/templates/api-server/statefulset.yaml
  charts/dependency-track/templates/frontend/deployment.yaml
  charts/dependency-track/values.yaml
  charts/hyades/Chart.yaml
  charts/hyades/templates/api-server/deployment.yaml
  charts/hyades/templates/frontend/deployment.yaml
  charts/hyades/templates/mirror-service/deployment.yaml
  charts/hyades/templates/notification-publisher/deployment.yaml
  charts/hyades/templates/repo-meta-analyzer/deployment.yaml
  charts/hyades/templates/vuln-analyzer/deployment.yaml
  charts/hyades/templates/vuln-analyzer/statefulset.yaml
  charts/hyades/values.yaml
Labels: enhancement

#150 Add `CODEOWNERS`
  CODEOWNERS
Labels: documentation
